controller_list:
  - name: Abb_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: Epson_C3_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - c3_joint_1
      - c3_joint_2
      - c3_joint_3
      - c3_joint_4
      - c3_joint_5
      - c3_joint_6
  - name: Epson_S5_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - s5_joint_1
      - s5_joint_2
      - s5_joint_3
      - s5_joint_4
      - s5_joint_5
      - s5_joint_6
  - name: Green_Kuka_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - iiwa2_joint_1
      - iiwa2_joint_2
      - iiwa2_joint_3
      - iiwa2_joint_4
      - iiwa2_joint_5
      - iiwa2_joint_6
      - iiwa2_joint_7
  - name: Blue_Kuka_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - iiwa1_joint_1
      - iiwa1_joint_2
      - iiwa1_joint_3
      - iiwa1_joint_4
      - iiwa1_joint_5
      - iiwa1_joint_6
      - iiwa1_joint_7